theme: jekyll-theme-hacker
title: Engineering Ladders
description: A framework for Engineering Managers

plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links
  
defaults:
  - values:
      layout: default